### PR TITLE
port to real litElement

### PR DESCRIPTION
**Pull request by filipbech**
The port is done and seems to be working, but I don't know how to generate the sw-precache file for the serviceworker... could you do it @larsgk ?

### CODE REVIEW

**Comment by larsgk** [comment]
Awesome and fast :) I'll try to figure out how the sw-precache should work
for the external files

**Comment by larsgk** [comment]
before merging - did you try that the live version still works? (because I'm using it for demos ;))

**Comment by filipbech** [comment]
Didn’t try with hardware. The UI plus microphone input seems to work...

**Comment by larsgk** [comment]
Cool :)

**Pull request merged**
